// Auth
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const FORGOT_PASSWORD_FAIL = 'FORGOT_PASSWORD_FAIL';
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL';
export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';
export const UPDATE_PASSWORD_ERROR = 'UPDATE_PASSWORD_ERROR';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';

// User
export const UPDATE_USER = 'UPDATE_USER';
export const GET_USER_BY_ID = 'GET_USER_BY_ID';
export const GET_USERS = 'GET_USERS';
export const GET_USER = 'GET_USER';
export const DELETE_USER = 'DELETE_USER';
export const CREATE_USER = 'CREATE_USER';
export const GET_USERS_BY_STORE = 'GET_USERS_BY_STORE';

// Vehicles
export const GET_VEHICLES = 'GET_VEHICLES';
export const GET_VEHICLE = 'GET_VEHICLE';
export const GET_VEHICLES_BY_MAKE = 'GET_VEHICLES_BY_MAKE';
export const CREATE_VEHICLE = 'CREATE_VEHICLE';
export const DELETE_VEHICLE = 'DELETE_VEHICLE';
export const UPDATE_VEHICLE = 'UPDATE_VEHICLE';

// Makes
export const GET_MAKES = 'GET_MAKES';
export const GET_MAKE = 'GET_MAKE';
export const CREATE_MAKE = 'CREATE_MAKE';
export const DELETE_MAKE = 'DELETE_MAKE';
export const UPDATE_MAKE = 'UPDATE_MAKE';

// Stores
export const GET_STORES = 'GET_STORES';
export const GET_STORES_BY_MAKE = 'GET_STORES_BY_MAKE';
export const GET_STORE = 'GET_STORE';
export const CREATE_STORE = 'CREATE_STORE';
export const DELETE_STORE = 'DELETE_STORE';
export const UPDATE_STORE = 'UPDATE_STORE';

// Document
export const GET_DOCUMENTS = 'GET_DOCUMENTS';
export const GET_DOCUMENTS_BY_STORE = 'GET_DOCUMENTS_BY_STORE';
export const GET_DOCUMENT = 'GET_DOCUMENT';
export const CREATE_DOCUMENT = 'CREATE_DOCUMENT';
export const DELETE_DOCUMENT = 'DELETE_DOCUMENT';
export const UPDATE_DOCUMENT = 'UPDATE_DOCUMENT';

// Status
export const GET_STATUSES = 'GET_ALL_STATUS';
export const GET_STATUS = 'GET_STATUS';
export const CREATE_STATUS = 'CREATE_STATUS';
export const DELETE_STATUS = 'DELETE_STATUS';
export const UPDATE_STATUS = 'UPDATE_STATUS';

// Sources
export const GET_SOURCES = 'GET_SOURCES';
export const GET_SOURCE = 'GET_SOURCE';
export const CREATE_SOURCE = 'CREATE_SOURCE';
export const DELETE_SOURCE = 'DELETE_SOURCE';
export const UPDATE_SOURCE = 'UPDATE_SOURCE';

// Mails
export const CREATE_MAIL = 'CREATE_MAIL';
export const CREATE_MAIL_ATTACHMENT = 'CREATE_MAIL_ATTACHMENT';

//MailJet
export const GET_SEGMENTATIONS = 'GET_SEGMENTATIONS';

// Activities
export const GET_ACTIVITIES = 'GET_ACTIVITIES';
export const GET_ACTIVITY = 'GET_ACTIVITY';
export const CREATE_ACTIVITY = 'CREATE_ACTIVITY';
export const DELETE_ACTIVITY = 'DELETE_ACTIVITY';
export const UPDATE_ACTIVITY = 'UPDATE_ACTIVITY';
export const GET_ACTIVITIES_BY_USER = 'GET_ACTIVITIES_BY_USER';
export const GET_ACTIVITIES_BY_LEAD = 'GET_ACTIVITIES_BY_STORE';
export const GET_ACTIVITIES_BY_OMSGLOBAL = 'GET_ACTIVITIES_BY_OMSGLOBAL';
export const GET_ACTIVITIES_BY_QUESTLEAD = 'GET_ACTIVITIES_BY_QUESTLEAD';
export const GET_ACTIVITIES_AR = 'GET_ACTIVITIES_AR';

// Comments
export const GET_COMMENTS_BY_LEAD = 'GET_COMMENTS_BY_LEAD';
export const CREATE_COMMENT = 'CREATE_COMMENT';
export const GET_COMMENTS_BY_OMSGLOBAL = 'GET_COMMENTS_BY_OMSGLOBAL';
export const GET_COMMENTS_BY_QUESTLEAD = 'GET_COMMENTS_BY_QUESTLEAD';
export const SET_COMMENTS = 'SET_COMMENTS';

// Alert
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

// Profile
export const GET_PROFILE = 'GET_PROFILE';
export const CREATE_PROFILE = 'CREATE_PROFILE';
export const GET_PROFILE_BY_USER = 'GET_PROFILE_BY_USER';

// Loading
export const SET_LOADING = 'SET_LOADING';

// Error
export const SET_ERROR = 'SET_ERROR';

// Success
export const SET_SUCCESS = 'SET_SUCCESS';

// Language
export const SET_LANGUAGE = 'SET_LANGUAGE';

// Clear States
export const CLEAR_STATE = 'CLEAR_STATE';
export const CLEAR_CHARTS_STATE = 'CLEAR_CHARTS_STATE';

// Charts
export const GET_CHART = 'GET_CHART';

//Oms Leads
export const GET_OMSGLOBAL = 'GET_OMSGLOBAL';
export const GET_OMSGLOBALS = 'GET_OMSGLOBALS';
export const GET_OMSGLOBALS_BY_STORE = 'GET_OMSGLOBALS_BY_STORE';
export const GET_OMSGLOBALS_BY_USER = 'GET_OMSGLOBALS_BY_USER';
export const UPDATE_OMSGLOBAL = 'UPDATE_OMSGLOBAL';
export const UPDATE_OMSGLOBAL_STATUS = 'UPDATE_OMSGLOBAL_STATUS';
export const DELETE_OMSGLOBAL = 'DELETE_OMSGLOBAL';
export const CREATE_OMSGLOBAL = 'CREATE_OMSGLOBAL';
export const GET_OMSGLOBALS_CHART = 'GET_OMSGLOBALS_CHART';
export const GET_OMSGLOBALS_BY_STATUS = 'GET_OMSGLOBALS_BY_STATUS';
export const GET_OMSGLOBALS_AR = 'GET_OMSGLOBALS_AR';
export const GET_OMSGLOBALS_SOLD = 'GET_OMSGLOBALS_SOLD';
export const GET_OMSGLOBALS_NEW = 'GET_OMSGLOBALS_NEW';
export const GET_OMSGLOBALS_FOLLOW = 'GET_OMSGLOBALS_FOLLOW';
export const GET_OMSGLOBALS_DATE = 'GET_OMSGLOBALS_DATE';
export const GET_LAST_OMSGLOBALS = 'GET_LAST_OMSGLOBALS';
export const GET_ALL_CHART_OMSGLOBALS = 'GET_ALL_CHART_OMSGLOBALS';

//Quest Leads
export const GET_QUESTLEAD = 'GET_QUESTLEAD';
export const GET_QUESTLEADS = 'GET_QUESTLEADS';
export const GET_QUESTLEADS_BY_STORE = 'GET_QUESTLEADS_BY_STORE';
export const GET_QUESTLEADS_BY_USER = 'GET_QUESTLEADS_BY_USER';
export const UPDATE_QUESTLEAD = 'UPDATE_QUESTLEAD';
export const DELETE_QUESTLEAD = 'DELETE_QUESTLEAD';
export const CREATE_QUESTLEAD = 'CREATE_QUESTLEAD';
export const GET_QUESTLEADS_CHART = 'GET_QUESTLEADS_CHART';
export const GET_QUESTLEADS_BY_STATUS = 'GET_QUESTLEADS_BY_STATUS';
export const GET_QUESTLEADS_AR = 'GET_QUESTLEADS_AR';
export const GET_QUESTLEADS_SOLD = 'GET_QUESTLEADS_SOLD';
export const GET_QUESTLEADS_NEW = 'GET_QUESTLEADS_NEW';
export const GET_QUESTLEADS_FOLLOW = 'GET_QUESTLEADS_FOLLOW';
export const GET_QUESTLEADS_DATE = 'GET_QUESTLEADS_DATE';
export const GET_LAST_QUESTLEADS = 'GET_LAST_QUESTLEADS';
export const GET_ALL_CHART_QUESTLEADS = 'GET_ALL_CHART_QUESTLEADS';

// Wsp
export const ADD_CONVERSATION = 'ADD_CONVERSATION';

// Companies 
export const CALL_USER = 'CALL_USER';

// Companies
export const GET_COMPANIES = 'GET_COMPANIES';
export const GET_COMPANY = 'GET_COMPANY';
export const CREATE_COMPANY = 'CREATE_COMPANY';
export const DELETE_COMPANY = 'DELETE_COMPANY';
export const UPDATE_COMPANY = 'UPDATE_COMPANY';

// Extras
export const LOAD_CSV = 'LOAD_CSV';
export const SET_DELETING_MANY = 'SET_DELETING_MANY';
export const CLEAR_ERROR = 'CLEAR_ERROR';
export const SET_VALUE = 'SET_VALUE';